### ISSUE TITLE
Why is the internet permission required?

### ISSUE THREAD

**Issue by benwaffle** [apcro/leafpicrevived#12]
https://reddit.com/r/fossdroid/comments/ei2htv/simple_gallery_now_relies_upon_proprietary/fcqd7ac?context=3

**Comment by apcro** [comment]
As a non-exhaustive answer based on the code, the INTERNET permission is used to allow the full changelog to be loaded from github (from the 'About' page, although this currently has a bug), as well as providing support for certain types of streaming playback using Android's exoplayer (mostly DRM support), and for showing Maps based on image metadata.

It certainly looks possible to adjust the whole package to not require the INTERNET permission however this would reduce existing functionality, especially for video playback.
