### ISSUE TITLE
Two identically-named options in the "open with" menu

### ISSUE THREAD

**Issue by yaomtc** [apcro/leafpicrevived#13]
When you install Leafpic Revived for the first time, and open an image from your files, of course Android prompts you which app you'd like to use to open it with. There are two new entries:
1. One is "Leafpic Revived", the viewer...
2. While the other is "Leafpic Revived", the... color picker(?) called Palette.

Which is an interesting tool, for sure, but it should probably be named differently if at all possible.

**Comment by MaheshPawaar** [comment]
While cloning project repo it is giving an error **keystore.properties (The system cannot find the file specified)**

**Comment by apcro** [comment]
> While cloning project repo it is giving an error **keystore.properties (The system cannot find the file specified)**

This is correct, the 'keystore.properties' file is one you need to create yourself, as it contains the passwords needed to sign your locally-built copy of the app. This file will have your own passwords in it.

**Comment by MaheshPawaar** [comment]
How should I make it ? Project is not setup on my machine. Gradle.build is failed.

**Comment by MaheshPawaar** [comment]
will I need to comment signing code in gradle file.

**Comment by MaheshPawaar** [comment]
I have generated debug key

**Comment by apcro** [comment]
sample `keystore.properties` file. Put this at the root of your repository:

```
storeFile=file({path to your keystore})
storePassword={store password}
keyAlias={key alias}
keyPassword={key password}
```
