### ISSUE TITLE
Cannot play video

### ISSUE THREAD

**Issue by fear-the-beaver** [apcro/leafpicrevived#15]
**Steps:**

1. Allow to display videos in a gallery.
2. Try to open a video file.

**Expected:**

1. The app plays video.

**Actual:**

1. Static fullscreen thumbnail is displayed.

![ezgif com-resize](https://user-images.githubusercontent.com/46751130/72070794-5afb2080-32b8-11ea-810a-dfd925ef87cd.gif)

**Workaround:**

1. Leaf can play the video when it opened via "Open with" button from the three dot menu.

**Environment:**

1. App version 0.8.2.20 from Fdroid.
2. Phone: oneplus 5t, OOS 9.0.10, android 9.

**Comment by endevdev** [comment]
I can confirm this issue and it's happening for gifs too

**Comment by apcro** [comment]
I need to do more research on this, but it appears to be related to the 'play' button location and size - 'play' only responds properly if you tap in the exact center of the screen; tapping elsewhere just shows.hides the menu, acting like an image.

**Comment by fear-the-beaver** [comment]
> I need to do more research on this, but it appears to be related to the 'play' button location and size - 'play' only responds properly if you tap in the exact center of the screen; tapping elsewhere just shows.hides the menu, acting like an image.

Can confirm, this works. But I've toggled instant play and still receive a preview with hidden play button instead.

**Comment by apcro** [comment]
More information: This is related to the https://github.com/mikepenz/Android-Iconics library, used for icons in various places, not showing the Play icon properly.

**Comment by apcro** [comment]
Further investigation shows this is related to the Theme library, not Iconics. Removing the internal call to the `refreshTheme()` override resolves the initial display issue.

**Comment by apcro** [comment]
Extended: https://github.com/mikepenz/Android-Iconics/issues/470 and https://github.com/mikepenz/Android-Iconics/issues/480 are related.
