### ISSUE TITLE
video play button invisable

### ISSUE THREAD

**Issue by NoahMarple** [apcro/leafpicrevived#24]
I could not figure how to play a video untill i found the trigger was invisible.
p.s the screenshot was talen with  "show layout bounds" turned on 
![2020_02_22_072730](https://user-images.githubusercontent.com/58449101/75101373-93756600-55a9-11ea-8943-57c8fcdfe15f.png)

**Comment by apcro** [comment]
This was fixed in 0.8.5, released a few days ago: 
https://github.com/apcro/leafpicrevived/commit/d08174589819297cfeb4d79a763a5240a66abae6
