### ISSUE TITLE
Copycat on Google Play

### ISSUE THREAD

**Issue by Poussinou** [apcro/leafpicrevived#29]
Hi @apcro 

I found this app: https://play.google.com/store/apps/details?id=com.miniapps.photoalbum on the Google Play Store. This guy just took your source code, added IAP in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove this copy from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GNU GPLv3 license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide some screenshots of your own app.

**Comment by apcro** [comment]
I've had a look at this, and it appears this version of the App was based on the original LeafPic source code (it has the wallpaper functionality apparently still enabled, and was also added a long time ago), and not the updated source I've been maintaining.
