### ISSUE TITLE
whye delete without confirmation

### ISSUE THREAD

**Issue by DoctorSubtilis** [apcro/leafpicrevived#30]
In my opinion, before deleting a photo, the app should ask for confirmation. Also because the delete button is very close to the share one.
Thanks

**Comment by bughunter2** [comment]
This is especially problematic when multiple files are selected. It's easy to make a mistake and delete many photos at once. I agree with @DoctorSubtilis, a confirmation would be helpful.

**Comment by apcro** [comment]
Confirmation of image deletion happens with deleting individual pictures. I will look at adding the confirmation when deleting multiple selected images in Gallery view.

**Comment by apcro** [comment]
I've fixed this issue now, as well as properly displaying the bottom sheet showing how many images were deleted. Updated release coming soon.
