### ISSUE TITLE
F-Droid updates not enabled

### ISSUE THREAD

**Issue by TacoTheDank** [apcro/leafpicrevived#34]
Check this out: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.alienpants.leafpicrevived.yml

I'll fix the tag pickup so that F-Droid can update the app.

This just requires that your tag names remain consistent. Please keep them preceded by a "v" from now on. Thanks.

(Also, another thing. I noticed you seemed to skip [the iconics bump and this](https://github.com/apcro/leafpicrevived/pull/32/commits/d8cebd7d7dc798bd8bf7573a3c05487d5b32ec90#diff-39e7d8c00954e920b98e7636f0ac30b2R112), was there something that broke? Also I could've easily redone the pull request to remove the leafpic to app commit that you didn't want, because the implementation commit is [massive](https://github.com/apcro/leafpicrevived/commit/f79d4d6c93858110939558233ee9499f57b5a663) and hard to read (instead of 9 relatively easy-to-read commits that all had their own distinct purpose. Just a gripe of mine.))

**Comment by apcro** [comment]
I am currently not updating the FDroid release, and I don't currently have any plans to support releases through FDroid/Gitlab given the seriousness of the problems I've had dealing with it.

**Comment by apcro** [comment]
Yes, I skipped the Iconics bump as every time I try and implement it, I run into issues with compiling the App, and I have ro revert it back to that specific beta version (even 4.0.2 breaks for some reason). It's in my personal backlog to do, just not something I've got to yet, since there are also breaking changes between v4 and v5 of Iconics.

**Comment by TacoTheDank** [comment]
Ah, ok that does clear things up. Thank you.

**Comment by apcro** [comment]
More on the Iconics bump: https://github.com/apcro/leafpicrevived/issues/21

**Comment by M86xKC** [comment]
Is there any alternative to download APK binaries from google Playtore since the f-droid version is outdated and no binaries are attached to GitHub releases page?
