### ISSUE TITLE
App crashes on Android Q

### ISSUE THREAD

**Issue by RB4915** [apcro/leafpicrevived#36]
public static String[] getProjection() {
return new String[]{
MediaStore.Files.FileColumns.PARENT,
MediaStore.Images.Media.BUCKET_DISPLAY_NAME,
"count(*)",
MediaStore.Images.Media.DATA,
"max(" + MediaStore.Images.Media.DATE_MODIFIED + ")"
};
}

that code above no longer work on android Q, please fix it
 it only shows when targetsdkVersion  29 compileSdkVersion 29, not on targetsdkVersion 28 and compileSdkVersion 28

**Comment by apcro** [comment]
This is a duplicate of #28 .
