### ISSUE TITLE
ProgressBar color in API Level 21

### ISSUE THREAD

**Issue by john2020star** [apcro/leafpicrevived#37]
Hi,

I found there is a bug in dialog_progress.xml. 

`                    <ProgressBar
                        android:id="@+id/progress_dialog_loading"
                        android:layout_width="@dimen/progress_circle_width_height"
                        android:layout_height="@dimen/progress_circle_width_height"
                        android:layout_gravity="center_vertical"
                        android:paddingRight="@dimen/sub_medium_spacing"
                        android:indeterminateTint="@color/md_white_1000" />`

You use android:indeterminateTint only to set the indeterminate color for ProgressBar. But it can cause a compatibility issue with showing color defined in colorAccent. To fix this issue, you can add android:indeterminateTintMode="src_in"

**Comment by apcro** [comment]
I've updated the code and this will be in a future release, however an additional change that is coming is an increase in the minSDK to 26.
