### ISSUE TITLE
Pinch to zoom support

### ISSUE THREAD

**Issue by wiktor-k** [apcro/leafpicrevived#4]
Hi,
I just found Leafpic revived and it works great: it's fast and beautiful.
One thing I'm missing though is enlarging images with pinch to zoom gesture.
Would thay be something in scope of Leafpic?

**Comment by apcro** [comment]
This is in the latest release (v0.8.2), which should be available on Google play now, but under a new bundleID: com.alienpants.leafpicrevived

https://play.google.com/store/apps/details?id=com.alienpants.leafpicrevived

**Comment by wiktor-k** [comment]
Hi, thanks for a quick feedback! I'm using FDroid that's still listing 0.8.1 but it's probably a matter of time.

Thank you and have a nice day! 👋
