### ISSUE TITLE
push F-Droid version to latest (0.8.7)

### ISSUE THREAD

**Issue by bughunter2** [apcro/leafpicrevived#41]
Hi, can you update the F-Droid version of the app? It's a couple of versions behind the one on Google Play.

**Comment by apcro** [comment]
There were too many issues the last time I tried to update the version on FDroid so I am not updating it anymore.

**Comment by bughunter2** [comment]
That's a pity, but very understandable. I know I've read comments by other developers sharing your sentiment.

**Comment by apcro** [comment]
I will expand on this a little:

I do like and support the intent behind FDroid, however the first time I added LeafPic Revived to FDroid it required a core update to one of the core libraries on my development machine to resolve an issue with FDroid's scripts, followed by a rewrite of FDroid's scripts to deal with the issue I ran in to (FDroid's scripts required bash > 5.0, the default on a Mac is 3.2, all of which took several days to figure out).

Subsequent attempts ran into multiple other problems, so I chose to stop updating FDroid and delete my GitLab account entirely.
