### ISSUE TITLE
App crashes on startup

### ISSUE THREAD

**Issue by Sogolumbo** [apcro/leafpicrevived#45]
When launching the app there's a grey screen for ~0.5 seconds. Then there's a black screen for ~0.2s, after that the app closes again.
(When the app is opened for the first time I get asked to confirm access to the file system, right after confirming that the app crashes).

Found in v0.8.7 from Fdroid on Android 6.0 (API 23).
According to the Google Play Store comments more people experience crashes.

**Comment by apcro** [comment]
v0.8.2 on FDroid is the latest version I have published. The v0.8.7 version was updated by someone else; I do not know if the source to that version corresponds to the one here, and I am not testing not releasing via FDroid anymore.

**Comment by Sogolumbo** [comment]
I tried the version from the google play store (v0.8.7) too. It's the same problem (crash right after confirming access to the file system).

**Comment by Sogolumbo** [comment]
Deleting all app data and cache didn't help (back on the F-Droid version).
