### ISSUE TITLE
no (pinch out) zoom available

### ISSUE THREAD

**Issue by DoctorSubtilis** [apcro/leafpicrevived#5]
I wander that a so nice app is without a so simple feature: zoom an image (pinching out). Why not?

**Comment by apcro** [comment]
V0.8.2 and up does support pinch to zoom to an extent. You can zoom in to a picture, but not out so far that the image becomes smaller than the device screen. Zoom in is also limited - it will zoom until the image is at 100% of size in pixels, not actually zoom (as in make the image itself larger for display purposes), so it's not possible to pinch-zoom to say 200% of the size of an image at the moment.

**Comment by DoctorSubtilis** [comment]
Thank you! However on F-Droid v.0.8.2 is not yet available: is it?
EDIT
Sorry, via web F-Droid shows your last release. I don't know why on smartphone it don't...
